create table if not exists public.hello_world_messages (
  id bigint generated by default as identity primary key,
  message text not null,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.hello_world_messages enable row level security;

grant select on table public.hello_world_messages to authenticated;

drop policy if exists "Authenticated users can read hello world messages" on public.hello_world_messages;

create policy "Authenticated users can read hello world messages"
  on public.hello_world_messages
  for select
  to authenticated
  using (true);